In [5]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
import numpy as np

A = scipy.array([ 
    [7, 3, -1, 2], 
    [3, 8, 1, -4], 
    [-1, 1, 4, -1], 
    [2, -4, -1, 6] 
    ])
B = scipy.array([ 
    [7, 3, -1, 2], 
    [3, 8, 1, -4], 
    [-1, 1, 4, -1], 
    [2, -4, -1, 6] 
    ])
P, L, U = scipy.linalg.lu(A)

In [6]:
A = scipy.array([ 
    [1,1,-1], 
    [1,-2,3], 
    [2,3,1], 
    ])
B = scipy.array([ 
    [4], 
    [-6], 
    [7],  
    ])
X = scipy.array([ 
    [1], 
    [2], 
    [-1],  
    ])
P, L, U = scipy.linalg.lu(A)

In [7]:
AA = A@P
XX = P@X

In [8]:
L

array([[1.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        ],
       [0.5       , 0.14285714, 1.        ]])

In [9]:
P@A

array([[ 2.,  3.,  1.],
       [ 1., -2.,  3.],
       [ 1.,  1., -1.]])

In [18]:
d = scipy.linalg.inv(L)@B

In [19]:
d

array([[ 4.        ],
       [-8.        ],
       [ 6.14285714]])

In [24]:
x = scipy.linalg.inv(U)@d

In [25]:
x

array([[-1.82417582],
       [ 1.01098901],
       [ 0.61538462]])

In [26]:
U

array([[ 2.        ,  3.        ,  1.        ],
       [ 0.        , -3.5       ,  2.5       ],
       [ 0.        ,  0.        , -1.85714286]])

In [28]:
d

array([[ 0.        ],
       [-2.        ],
       [-1.14285714]])

In [61]:
U = scipy.array([ 
    [1,1,-1], 
    [0,-3,4], 
    [0,0,13/3], 
    ])
L = scipy.array([ 
    [1,0,0], 
    [1,1,0], 
    [2,-1/3,1], 
    ])

In [62]:
L@U

array([[ 1.,  1., -1.],
       [ 1., -2.,  3.],
       [ 2.,  3.,  1.]])

In [107]:
def my_LU(A):
    n = A.shape[0]
    A = np.array(A)

    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U


In [108]:
my_LU(A)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'